insert into author (id_author, first_name, last_name) values (1, 'Bob', 'Dylan');
insert into author (id_author, first_name, last_name) values (2, 'Paul', 'McCartney');
insert into author (id_author, first_name, last_name) values (3, 'Stevie', 'Wonder');
insert into author (id_author, first_name, last_name) values (4, 'Bob', 'Marley');
insert into author (id_author, first_name, last_name) values (5, 'Elton', 'John');
insert into author (id_author, first_name, last_name) values (6, 'Glenn', 'Danzig');
insert into author (id_author, first_name, last_name) values (7, 'Marshall ', 'Mathers');
insert into author (id_author, first_name, last_name) values (8, 'James', 'Hetfield');
insert into author (id_author, first_name, last_name) values (9, 'Michael ', 'Jackson');
insert into author (id_author, first_name, last_name) values (10, 'Kurt', 'Cobain');
insert into author (id_author, first_name, last_name) values (11, 'David', 'Bowie');
insert into author (id_author, first_name, last_name) values (12, 'Dolly', 'Parton');
insert into author (id_author, first_name, last_name) values (13, 'Kanye', 'West ');
insert into author (id_author, first_name, last_name) values (14, 'Fatboy', 'Slim');
insert into author (id_author, first_name, last_name) values (15, 'George', 'Michael');
insert into author (id_author, first_name, last_name) values (16, 'Marina', 'Tucaković');