insert into performer(id_performer, first_name, last_name) values (1, 'George', 'Michael');
insert into performer(id_performer, first_name, last_name) values (2, 'Fatboy', 'Slim');
insert into performer(id_performer, first_name, last_name) values (3, 'Jimi', 'Hendrix');
insert into performer(id_performer, band_name) values (4, 'Wham!');
insert into performer(id_performer, first_name) values (5, 'Eminem');
insert into performer (id_performer, band_name) values (6, 'Nirvana');
insert into performer (id_performer, band_name) values (7, 'U2');
insert into performer (id_performer, band_name) values (8, 'Metallica');
insert into performer (id_performer, band_name) values (9, 'Beatles');
insert into performer (id_performer, first_name, last_name) values (10, 'Bob', 'Marley');
insert into performer (id_performer, first_name, last_name) values (11, 'Zdravko', 'Čolić');
insert into performer (id_performer, first_name, last_name) values (12, 'Dolly', 'Parton');
insert into performer (id_performer, first_name, last_name) values (13, 'Iggy', 'Pop');
insert into performer (id_performer, first_name, last_name) values (14, 'Michael ', 'Jackson');
insert into performer (id_performer, band_name) values (15, 'Misfits');
insert into performer (id_performer, first_name, last_name) values (16, 'Kate ', 'Bush');
insert into performer (id_performer, band_name) values (17, 'Pointer Sisters');
insert into performer (id_performer, first_name, last_name) values (18, 'Kanye', 'West');